# Generated by Django 4.0.4 on 2022-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_reservations_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('u', 'Unavailable'), ('x', 'Temporarily Blocked')], default='a', max_length=1),
        ),
    ]
