# Generated by Django 4.0.4 on 2022-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_workstations_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstations',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
