# Generated by Django 4.0.4 on 2022-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_alter_workstations_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstations',
            name='sector',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
